# The docker compose file for running the infrastructure
# services for development purposes.

version: '3.8'
volumes:
    mongo_data:
services:
    byteartretail-mongo:
        image: daxnet/byteartretail-mongo
        build:
            context: docker/mongo
            dockerfile: Dockerfile
